--enable-features=WaylandWindowDecorations
--ozone-platform-hint=auto
--js-flags='--jitless' 
#--disable-gpu 
# --enable-features=VaapiVideoDecodeLinuxGL,VaapiVideoEncoder,ChromeRefresh2023 
#--use-gl=angle 
#--use-angle=gl 
