[background]
# Full path to image or directory of images
image = /home/work/Downloads/wallpaper.jpg
# How to fit the image to screens
# One of: fill_and_crop, preserve_aspect, stretch
fill_mode = fill_and_crop


[panel]
# widgets_* is a space-separated list of widgets to be displayed
# at the corresponding part of the panel
# Supported widgets are: launchers clock network battery window-list volume menu notifications tray command-output
# Special widgets are "spacing" and "separator" widgets, they can be used to add padding everywhere on the panel
# To use them, just append the amount of pixels you want as a padding
# to the word "spacing" or "separator" and use it as a plugin
widgets_left = menu spacing4 window-list
widgets_center = none
widgets_right = volume battery clock

# The minimal size of the panel. Note that some widgets might force panel bigger than this size.
# All widgets also have individual settings for size
# Changing this requires a panel restart
minimal_height = 5
position = bottom
background_color = \#eff1f5cc

 Configuration for the launchers widget
# can be a desktop file

# spacing between widgets, can be negative
launchers_spacing = 4

# size of the launcher icon
launchers_size = 24

clock_format = %d %b %l:%M:%S %P
clock_font = JetBrains Mono

volume_icon_size = 24
