#!/bin/bash
build() {
    add_file "/etc/ipe_setup/hardened.policy.p7b"
    add_file "/etc/ipe_setup/hardened.policy"
    add_runscript
}
help() {
    echo "Loads and activates the hardened IPE policy before switch_root."
}
